+incdir+$MY_TINYRISCV_HOME/src/core
$MY_TINYRISCV_HOME/src/core/defines.v
$MY_TINYRISCV_HOME/src/core/pc_reg.v
$MY_TINYRISCV_HOME/src/core/id.v
$MY_TINYRISCV_HOME/src/core/regs.v
$MY_TINYRISCV_HOME/src/core/ex.v
$MY_TINYRISCV_HOME/src/core/ctrl.v
$MY_TINYRISCV_HOME/src/core/csr_reg.v
$MY_TINYRISCV_HOME/src/core/clint.v
$MY_TINYRISCV_HOME/src/core/div.v
$MY_TINYRISCV_HOME/src/core/tinyriscv.v
